M48
; DRILL file KiCad 10.0.7 date 2026-10-10T23:56:10
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-10-10T23:56:10+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X0.122Y0.3058
X0.3504Y0.3058
T2
X0.6039Y0.374
M30
